/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelesMenus;

//<editor-fold defaultstate="collapsed" desc="imports">
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.System.out;
import javax.swing.JPanel;
import javax.swing.Timer;
//</editor-fold>

/**
 *
 * @author David
 */
public class PMenu extends JPanel implements ActionListener {

    
    /**
     * Creates new form Menu1
     */
    public PMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNVisitantes = new javax.swing.JLabel();
        eTVisitantes = new javax.swing.JLabel();

        eNVisitantes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eNVisitantes.setText("0");

        eTVisitantes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eTVisitantes.setText("Visitantes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(eTVisitantes)
                .addGap(18, 18, 18)
                .addComponent(eNVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTVisitantes)
                    .addComponent(eNVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eNVisitantes;
    private javax.swing.JLabel eTVisitantes;
    // End of variables declaration//GEN-END:variables
    
    int mod(int n, int mod) {
        return n%mod;
    }
    
    /* 1 visitante por segundo real 1s=1h 12h(s) abierto dia 12h(s) cerrado noche
     * hora apertura 6 mañana hora cierra 12 noche
     * update
     */
    void actualiza(int t) {
        //24 horas {0...23}
        int h=mod(t,24);
        
        eNVisitantes.setText(Integer.toString(h));
        
        if (t>5) {
            out.println("abierto dia");
        }
    }
    
    int t = 0;
    
    //<editor-fold defaultstate="collapsed" desc="actionperformed">
    @Override
    public void actionPerformed(ActionEvent e) {
        //out.println("hola");
        actualiza(t);
        t++;
    }
//</editor-fold>
}
