/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

//<editor-fold defaultstate="collapsed" desc="imports">
import javax.swing.JFrame;
import javax.swing.JScrollPane;
//</editor-fold>

/**
 *
 * @author David
 * TODO
 * ocultar los sliders 
 * arrastra con el raton sin sliders
 */
public class VPN extends JFrame {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables

    //<editor-fold defaultstate="collapsed" desc="constructor">
    /**
     * Creates new form VPN
     */
    public VPN() {
        initComponents();
    }
//</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="getters">
    public JScrollPane getjScrollPane() {
        return jScrollPane;
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="toString">
    @Override
    public String toString() {
        return "VPN{" + "jScrollPane=" + jScrollPane + '}';
    }
//</editor-fold>
}
